set positional-arguments

test:
    poetry run pytest

alias ti := test-interview
@test-interview interview_num test_filter="":
    poetry run pytest tests/codint/interviews/test_solution_interview_{{interview_num}}.py -k "{{test_filter}}"

alias tm := test-mandatory
@test-mandatory mandatory_name test_filter="":
    poetry run pytest tests/codint/mandatory/test_solution_{{mandatory_name}}.py -k "{{test_filter}}"
